In [14]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [15]:
train_data = pd.read_excel('train.xlsx')

X = train_data.drop('target', axis=1)
y = train_data['target']

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)

y_val_pred = rf_classifier.predict(X_val)
val_accuracy = accuracy_score(y_val, y_val_pred)
print(f"Validation Accuracy: {val_accuracy:.3f}")

Validation Accuracy: 0.986

In [17]:
test_data = pd.read_excel('test.xlsx')
X_test = test_data.copy()  

y_test_pred = rf_classifier.predict(X_test)

test_data['predicted_target'] = y_test_pred

test_data.to_csv('test.csv', index=False)

print("Predictions added to 'test.csv'")

Predictions added to 'test.csv'

In [13]:
df=pd.read_csv('test.csv')
df.head()

,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,predicted_target
0,-76.0,-83.0,-70.0,-66.0,-64.0,-72.0,-64.0,-69.0,-60.0,-76.0,-83.0,-78.0,-81.0,-81.0,-81.0,-70.0,-60.0,-60.0,B74
1,-58.0,-57.0,-78.0,-81.0,-73.0,-73.0,-78.0,-78.0,-82.0,-49.0,-55.0,-58.0,-66.0,-79.0,-72.0,-83.0,-74.0,-80.0,A10
2,-70.0,-70.0,-71.0,-69.0,-69.0,-68.0,-61.0,-55.0,-53.0,-82.0,-87.0,-76.0,-68.0,-57.0,-64.0,-75.0,-57.0,-70.0,B65
3,-71.0,-61.0,-56.0,-56.0,-61.0,-60.0,-68.0,-66.0,-72.0,-58.0,-55.0,-56.0,-58.0,-62.0,-61.0,-59.0,-64.0,-65.0,B20
4,-72.0,-71.0,-64.0,-69.0,-64.0,-63.0,-61.0,-42.0,-55.0,-61.0,-69.0,-67.0,-63.0,-63.0,-55.0,-49.0,-49.0,-57.0,A67